server.port=8888
spring.application.name=config-server

# Point to your public GitHub repository
spring.cloud.config.server.git.uri=https://github.com/Nitinkuma1/config-server-repo.git

# Specify the default branch (usually 'main' or 'master')
spring.cloud.config.server.git.default-label=main
